// Generated by CoffeeScript 1.4.0
(function() {
  var global, __;

  global = Function('return this')();

  __ = function(msgid) {
    var _ref;
    if ((_ref = global.po) != null ? _ref[msgid] : void 0) {
      return global.po[msgid];
    }
    return msgid;
  };

  global.__ = __;

}).call(this);
